name = "Xenyria Client Modpack"
author = "Xenyria Team"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfc0ec87014cfa8cc3bd65bb335b939d441d9b8165156fe00e9370ed945c4aa4"

[versions]
fabric = "0.14.19"
minecraft = "1.19.4"
